default_platform(:android)

platform :android do
  desc "Build and deploy a new version to Google Play Internal Testing"
  lane :deploy_internal do

    gradle(
      task: 'clean bundle',
      build_type: 'Release',
    )

    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true
    )

  end
end