name: Release apk artifact

on:
  push:
    tags:
      - 'v*'



jobs:
  create-release:
    name: Build signed apk
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > app/google-services.json

      - name: Grant gradlew execute permissions
        run: chmod +x gradlew

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Create the release
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"




      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}
          name: Release ${{ github.ref_name }}


  create-firebase-release:
    name: Create firebase release
    needs: create-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant gradlew permission
        run: chmod +x gradlew

      - name: Create Google services
        run: echo "${{ secrets.GOOGLE_SERIVCES }}" | base64 --decode > app/google-services.json

      - name: Build Dev release for firebase
        run: ./gradlew assembleDebug

      - name: Create firebase upload
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL }}
          groups: "testers"
          file: app/build/outputs/apk/debug/app-debug.apk


  deploy-to-play-store:
    name: Deploy to Google Play Internal Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundle-cache: true

      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > app/google-services.json

      - name: Create Play Store API Credentials JSON
        run: echo "${{ secrets.PLAY_STORE_CREDENTIAL }}" | base64 --decode > play-store-credentials.json

      - name: Decode Keystore File
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > app/release-keystore.jks

      - name: Grant gradlew permission
        run: chmod +x gradlew

      - name: Run Fastlane Deployment
        run: fastlane deploy_internal
        env:
          RELEASE_KEYSTORE_PATH: "app/release-keystore.jks"
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}